
dist: xenial
sudo: required

language: c

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential
    - sudo apt-get install -y linux-headers-generic
    - sudo apt-get install -y linux-libc-dev
    - sudo apt-get install -y cmake
    - sudo apt-get install -y git

script:
    - mkdir Debug
    - cd Debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
